# Generated by Django 4.0.4 on 2022-05-25 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=128, verbose_name='Название проекта')),
                ('users_project', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=200, verbose_name='Текст заметки')),
                ('todo_date_create', models.DateTimeField(verbose_name='Время создания заметки')),
                ('todo_date_update', models.DateTimeField(verbose_name='Время изменения заметки')),
                ('todo_open_close', models.BooleanField(default=True, verbose_name='Открыта или зактыта ToDo')),
                ('todo_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_project.project')),
                ('todo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'ToDo-s',
            },
        ),
    ]
